name: Swift

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.swift'
      - '.github/workflows/swift.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.swift'
      - '.github/workflows/swift.yml'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    # swift test commented, thread do not work properly
    #- name: Run tests
    #  run: swift test -v
